# Generated by Django 3.1.7 on 2021-02-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolaosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='rodada',
            field=models.IntegerField(blank=True, null=True, verbose_name='gols_time1'),
        ),
    ]
